### ISSUE TITLE
The README shouldn't advertise non-existent functionality

### ISSUE THREAD

**Issue by ItsHarper** [Eeshwar-Krishnan/PhotonFTC#1]
The README says that PhotonCore "speed[s] up and paralleli[zes] the FTC control system for faster loop times", but the only source code it has is an `AndroidManifest.xml` file. Am I missing something?

**Comment by Eeshwar-Krishnan** [comment]
Good catch, the disclaimer that Photon is not available yet was accidentally removed during a merge. Fixed
