### ISSUE TITLE
Motor Direction Reversed

### ISSUE THREAD

**Issue by ColemanDuPlessie** [Eeshwar-Krishnan/PhotonFTC#12]
First off, thank you for creating and maintaining PhotonFTC, it's a great resource!

After adding PhotonFTC (version 3.0.1 alpha) to my FTC team's codebase, the motors connected to our Control Hub (but not Expansion Hub) began spinning in the opposite direction. The Expansion Hub is connected via RS485, and not USB, so that may explain why only half of the motors reversed.

It's not a big issue to correct in code (just reversing the motor directions worked fine), but it's a strange thing to happen. If it matters, the only way we use Photon is by adding @Photon to an abstract OpMode that all of our OpModes are subclasses of.

**Comment by Eeshwar-Krishnan** [comment]
Thanks for the insight! May I ask what motors you are running?

**Comment by ColemanDuPlessie** [comment]
All GoBilda 5203s.

**Comment by j5155** [comment]
Can recreate; installing/uninstalling photon reversed all motors and encoders on my control hub (no photon on expansion hub as it isn't connected over USB)
This issue caused us to slam full speed into opponents match 2 of state; please fix!!

**Comment by edinapieceofcake3763** [comment]
We think we have found a fix to this reverse motor issue.

Can we get write access so we can create a branch for the PR?

**Comment by qwertychouskie** [comment]
> Can we get write access so we can create a branch for the PR?

You shouldn't need write access to the main repo to create a PR, just fork the repo, make the change in a branch their, then make the PR back to the main repo.

**Comment by Eeshwar-Krishnan** [comment]
Fixed in 3.0.1
