### ISSUE TITLE
Please log whenever PhotonFTC gets enabled

### ISSUE THREAD

**Issue by ItsHarper** [Eeshwar-Krishnan/PhotonFTC#14]
It's important for anyone helping a team by looking at their logs to be able to tell whether or not they're using PhotonFTC.

**Comment by Eeshwar-Krishnan** [comment]
Looks like this was mistakenly removed in the 2.0 Core, and will be added back for the next patch version bump.

Just for reference: Is there more specific data you would like to have logged? I'll have it logging when its enabled, and I can also have it attempt to log if a Photon Lynx Message is being used in passthrough mode when Photon is disabled as well.

**Comment by Eeshwar-Krishnan** [comment]
Fixed in 3.0.1
